#!/bin/bash

MYSQL_STORAGE_DEVICE=/dev/sda
STRAPI_STORAGE_DEVICE=/dev/sdb
DOCKER_VOLUME_DIR=.docker-volume

DATABASE_DIR=$DOCKER_VOLUME_DIR/database
STRAPI_DIR=$DOCKER_VOLUME_DIR/strapi

mkdir -pv $DATABASE_DIR
mkdir -pv $STRAPI_DIR

mount $MYSQL_STORAGE_DEVICE $DATABASE_DIR 
mount $STRAPI_STORAGE_DEVICE $STRAPI_DIR

mkdir -p $STRAPI_DIR/uploads

